//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Tommy/Script/Inputs/MainInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace PlayerInput
{
    public partial class @MainInputs: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @MainInputs()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainInputs"",
    ""maps"": [
        {
            ""name"": ""Cart"",
            ""id"": ""ab38f77a-0c38-4829-b954-0844bed98e45"",
            ""actions"": [
                {
                    ""name"": ""CartForward"",
                    ""type"": ""Value"",
                    ""id"": ""af42b16c-ba6f-408f-b92d-503494fc27d8"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CartBackward"",
                    ""type"": ""Value"",
                    ""id"": ""77cd7733-3d9a-4818-9235-6f09a7b60448"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Test2"",
                    ""type"": ""Button"",
                    ""id"": ""b9b01c8d-e0c5-43cc-b6a4-3234a677c7b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""459baca9-0066-446e-9c31-5034ff83dc42"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CartForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10cef959-29e6-4bdb-8310-2a5d4d9831d9"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CartBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67b2494a-7ee7-4e13-8e85-f6055c2b31ea"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a1166a5-4b1e-4cf6-8e64-cb50cca55a47"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Cart
            m_Cart = asset.FindActionMap("Cart", throwIfNotFound: true);
            m_Cart_CartForward = m_Cart.FindAction("CartForward", throwIfNotFound: true);
            m_Cart_CartBackward = m_Cart.FindAction("CartBackward", throwIfNotFound: true);
            m_Cart_Test2 = m_Cart.FindAction("Test2", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Cart
        private readonly InputActionMap m_Cart;
        private List<ICartActions> m_CartActionsCallbackInterfaces = new List<ICartActions>();
        private readonly InputAction m_Cart_CartForward;
        private readonly InputAction m_Cart_CartBackward;
        private readonly InputAction m_Cart_Test2;
        public struct CartActions
        {
            private @MainInputs m_Wrapper;
            public CartActions(@MainInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @CartForward => m_Wrapper.m_Cart_CartForward;
            public InputAction @CartBackward => m_Wrapper.m_Cart_CartBackward;
            public InputAction @Test2 => m_Wrapper.m_Cart_Test2;
            public InputActionMap Get() { return m_Wrapper.m_Cart; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CartActions set) { return set.Get(); }
            public void AddCallbacks(ICartActions instance)
            {
                if (instance == null || m_Wrapper.m_CartActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CartActionsCallbackInterfaces.Add(instance);
                @CartForward.started += instance.OnCartForward;
                @CartForward.performed += instance.OnCartForward;
                @CartForward.canceled += instance.OnCartForward;
                @CartBackward.started += instance.OnCartBackward;
                @CartBackward.performed += instance.OnCartBackward;
                @CartBackward.canceled += instance.OnCartBackward;
                @Test2.started += instance.OnTest2;
                @Test2.performed += instance.OnTest2;
                @Test2.canceled += instance.OnTest2;
            }

            private void UnregisterCallbacks(ICartActions instance)
            {
                @CartForward.started -= instance.OnCartForward;
                @CartForward.performed -= instance.OnCartForward;
                @CartForward.canceled -= instance.OnCartForward;
                @CartBackward.started -= instance.OnCartBackward;
                @CartBackward.performed -= instance.OnCartBackward;
                @CartBackward.canceled -= instance.OnCartBackward;
                @Test2.started -= instance.OnTest2;
                @Test2.performed -= instance.OnTest2;
                @Test2.canceled -= instance.OnTest2;
            }

            public void RemoveCallbacks(ICartActions instance)
            {
                if (m_Wrapper.m_CartActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICartActions instance)
            {
                foreach (var item in m_Wrapper.m_CartActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CartActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CartActions @Cart => new CartActions(this);
        public interface ICartActions
        {
            void OnCartForward(InputAction.CallbackContext context);
            void OnCartBackward(InputAction.CallbackContext context);
            void OnTest2(InputAction.CallbackContext context);
        }
    }
}
